baseURL = "https://example.org/"
languageCode = "en-us"
title = "Pokedex"

[params]
  author = "Odhy Pradhana"

# Hugo Module version requirement
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
